### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by schmidp** [k8sgpt-ai/k8sgpt#599]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.13

### Kubernetes Version

v1.27.4+k3s1

### Host OS and its Version

macOS 13.4.1 (c) 

### Steps to reproduce

```
brew tap k8sgpt-ai/k8sgpt
brew install k8sgpt 
k8sgpt generate
k8sgpt auth add -b openai -m gpt-3.5-turbo
k8sgpt analyze 
```

leads to:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1046d3978]

goroutine 48 [running]:
github.com/k8sgpt-ai/k8sgpt/pkg/analyzer.IngressAnalyzer.Analyze({}, {0x14000e01800, {0x1054bfab8, 0x14000126018}, {0x0, 0x0}, {0x1054c01f0, 0x1067a6600}, 0x0, {0x0, ...}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analyzer/ingress.go:102 +0xc58
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis.func1({0x1054a4580, 0x1067ebc90}, 0x14000a067c0?, 0x140009baaf8?)
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:171 +0xac
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:169 +0x8e8
```

### Expected behaviour

no crash

### Actual behaviour

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1046d3978]

goroutine 48 [running]:
github.com/k8sgpt-ai/k8sgpt/pkg/analyzer.IngressAnalyzer.Analyze({}, {0x14000e01800, {0x1054bfab8, 0x14000126018}, {0x0, 0x0}, {0x1054c01f0, 0x1067a6600}, 0x0, {0x0, ...}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analyzer/ingress.go:102 +0xc58
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis.func1({0x1054a4580, 0x1067ebc90}, 0x14000a067c0?, 0x140009baaf8?)
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:171 +0xac
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:169 +0x8e8
```

**Comment by AlexsJones** [comment]
This looks like an issue with Ingress where there are no HTTP paths setup.
Can you please try to disable Ingress filter to validate this theory?

```
k8sgpt filters remove Ingress
```

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
> This looks like an issue with Ingress where there are no HTTP paths setup. Can you please try to disable Ingress filter to validate this theory?
> 
> ```
> k8sgpt filters remove Ingress
> ```

I ran into the same error and can confirm removing the Ingress filter as you asked caused the command to succeed.

Does this mean none of my Ingresses will be analyzed now?
